### ISSUE TITLE
Log In doesn't work and no way to Sign Up

### ISSUE THREAD

**Issue by ghost** [Temtem-Interactive-Map/Temzone-Desktop#24]
There is no way to sign up so I tracked down the mobile app to make an account and trying to log in with that doesn't work either.

**Comment by TheLokin** [comment]
I would like to begin by expressing my apologies for the delay in my response. Secondly, it is important to clarify that our desktop application has a distinct focus when compared to the mobile version, as it is specifically designed for users with an administrative role. The primary reason for the inability to create new accounts through the desktop application is to ensure that only duly authorized individuals can access the sensitive information it manages.

To access the desktop application, it is essential to have a previously registered account with the appropriate administrator permissions. This restriction is in place to maintain the security of the application and the information it handles, which is why accounts created from the mobile application do not function in the desktop version.

In order to address your issue, I would recommend considering the option of creating a customized version of the desktop application. This would allow you to integrate it with Firebase services over which you have full control, thereby enabling you to generate users with administrator roles. The detailed process for carrying out this configuration is explained in the README file of our application. However, if you have any additional questions or require further guidance on this procedure, please do not hesitate to contact me. I am here to provide the assistance you need.
